# Generated by Django 4.1.1 on 2022-10-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universaltennis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("rank", models.PositiveIntegerField(unique=True)),
                (
                    "min_utr",
                    models.DecimalField(decimal_places=14, max_digits=16),
                ),
                (
                    "max_utr",
                    models.DecimalField(decimal_places=14, max_digits=16),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="PlayerAlternateName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "alternate_names",
                    models.ManyToManyField(
                        blank=True, null=True, to="ranking.playeralternatename"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ranking.category",
                    ),
                ),
                (
                    "utr_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="universaltennis.player",
                    ),
                ),
            ],
        ),
    ]
