# Generated by Django 4.1.1 on 2022-10-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "singles_utr",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=16, null=True
                    ),
                ),
                (
                    "rating_status_singles",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "doubles_utr",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=16, null=True
                    ),
                ),
                (
                    "rating_status_doubles",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "my_utr_singles",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=16, null=True
                    ),
                ),
                (
                    "my_utr_status_singles",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "my_utr_doubles",
                    models.DecimalField(
                        blank=True, decimal_places=14, max_digits=16, null=True
                    ),
                ),
                (
                    "my_utr_status_doubles",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "my_utr_singles_reliability",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "my_utr_doubles_reliability",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "member_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
        ),
    ]
